### ISSUE TITLE
ImportError: Bio.Alphabet has been removed from Biopython.

### ISSUE THREAD

**Issue by neelam19051** [danillo-alvarenga/tncomp_finder#2]
.Hi, I am facing this error and i followed below instruction also but still unable to solve it.
**/TnComp_finder.py**
./TnComp_finder.py:247: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if character is 'T':
./TnComp_finder.py:249: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif character is 'A':
./TnComp_finder.py:251: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif character is 'C':
./TnComp_finder.py:253: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif character is 'G':
./TnComp_finder.py:255: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif character is 'N':
./TnComp_finder.py:275: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if item[3] is '+':
./TnComp_finder.py:278: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif item[3] is '-':
Traceback (most recent call last):
  File "./TnComp_finder.py", line 31, in <module>
    from Bio.Alphabet import IUPAC
  File "/home/bvs/.local/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

Thank you!

**Comment by Holert** [comment]
From https://biopython.org/wiki/Alphabet

Try removing the references to Alphabet from the script:

Line 31: remove "from Bio.Alphabet import IUPAC"
Line 438: change "gbk_record = SeqRecord(Seq(sequence, IUPAC.unambiguous_dna)" to "gbk_record = SeqRecord(Seq(sequence)"

**Comment by pengxyii** [comment]
Hello, 
I use  tncomp_finder on a  archaeal genome，and facing this error:
Traceback (most recent call last):
  File "/home/pengxy/mambaforge/envs/tncomp_finder/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/pengxy/mambaforge/envs/tncomp_finder/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/home/pengxy/data/software/tncomp_finder/TnComp_finder.py", line 170, in parse_blastn
    write_report(candidates, outdir)
  File "/home/pengxy/data/software/tncomp_finder/TnComp_finder.py", line 326, in write_report
    seq_info.update({key:[transposon, extended_seq]})
                                      ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'extended_seq' where it is not associated with a value
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pengxy/data/software/tncomp_finder/TnComp_finder.py", line 609, in <module>
    main()
  File "/home/pengxy/data/software/tncomp_finder/TnComp_finder.py", line 598, in main
    Pool(args.processors).map(partial(parse_blastn, outdir=args.out), args.files)
  File "/home/pengxy/mambaforge/envs/tncomp_finder/lib/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pengxy/mambaforge/envs/tncomp_finder/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
UnboundLocalError: cannot access local variable 'extended_seq' where it is not associated with a value

Do you know why that is?
Thank you
